# 多服务器配置文件
# 支持动态添加/删除服务器配置，无需重启服务

# 全局设置
global_settings:
  # 默认服务器（当用户未指定服务器编号时使用）
  default_server: "server_1"
  
  # API请求配置
  api_timeout: 30
  api_retry_times: 3
  api_retry_delay: 1.0
  
  # 缓存配置
  enable_cache: true
  cache_expire_time: 300
  
  # 健康检查配置
  enable_auto_health_check: true
  health_check_interval: 5

# 服务器配置列表
servers:
  # 服务器1配置
  server_1:
    # 服务器基本信息
    name: "AAA服务器"
    display_name: "AAA"
    description: "主要游戏服务器"
    
    # 连接信息
    api_base_url: "http://127.0.0.1:8010/api"
    api_token: "${CRCON_API_TOKEN}"  # 支持环境变量
    
    # 服务器特定设置
    max_players: 100
    region: "Asia"
    timezone: "Asia/Shanghai"
    
    # 功能开关
    enabled: true
    maintenance_mode: false
    
    # 权限配置（可选，如果不配置则使用全局权限）
    admin_groups: []
    player_groups: []
    
    # 自定义参数
    custom_params:
      server_type: "warfare"
      language: "zh-CN"

  # 服务器2配置
  server_2:
    name: "BBB服务器"
    display_name: "BBB"
    description: "备用游戏服务器"
    
    api_base_url: "http://127.0.0.1:8011/api"
    api_token: "${CRCON_API_TOKEN}"
    
    max_players: 100
    region: "Asia"
    timezone: "Asia/Shanghai"
    
    enabled: true
    maintenance_mode: false
    
    admin_groups: []
    player_groups: []
    
    custom_params:
      server_type: "warfare"
      language: "zh-CN"

  # 服务器3配置
  server_3:
    name: "CCC服务器"
    display_name: "CCC"
    description: "测试服务器"
    
    api_base_url: "http://127.0.0.1:8012/api"
    api_token: "${CRCON_API_TOKEN}"
    
    max_players: 50
    region: "Asia"
    timezone: "Asia/Shanghai"
    
    enabled: true
    maintenance_mode: false
    
    admin_groups: []
    player_groups: []
    
    custom_params:
      server_type: "skirmish"
      language: "zh-CN"

  # 服务器4配置
  server_4:
    name: "DDD服务器"
    display_name: "DDD"
    description: "活动服务器"
    
    api_base_url: "http://127.0.0.1:8013/api"
    api_token: "${CRCON_API_TOKEN}"
    
    max_players: 100
    region: "Asia"
    timezone: "Asia/Shanghai"
    
    enabled: true
    maintenance_mode: false
    
    admin_groups: []
    player_groups: []
    
    custom_params:
      server_type: "warfare"
      language: "zh-CN"

# 服务器组配置（可选）
server_groups:
  # 主要服务器组
  main_servers:
    name: "主要服务器"
    servers: ["server_1", "server_2"]
    description: "主要的游戏服务器"
  
  # 测试服务器组
  test_servers:
    name: "测试服务器"
    servers: ["server_3"]
    description: "用于测试的服务器"
  
  # 活动服务器组
  event_servers:
    name: "活动服务器"
    servers: ["server_4"]
    description: "用于特殊活动的服务器"

# 服务器别名配置（支持用户使用别名访问服务器）
server_aliases:
  "1": "server_1"
  "2": "server_2"
  "3": "server_3"
  "4": "server_4"
  "AAA": "server_1"
  "BBB": "server_2"
  "CCC": "server_3"
  "DDD": "server_4"
  "主服": "server_1"
  "备服": "server_2"
  "测试服": "server_3"
  "活动服": "server_4"