# 权限组配置文件
# 支持多个服务器组，每个组可以绑定多个游戏服务器实例
# 每个服务器组的QQ号配置独立存储且互不干扰

# 服务器组配置
server_groups:
  # 服务器组A - 示例配置
  group_a:
    # 服务器组名称
    name: "服务器组A"
    # 服务器组描述
    description: "主要服务器组，包含核心游戏服务器"
    # 绑定的游戏服务器实例列表
    game_servers:
      - server_id: 1
        name: "AAA服务器"
        api_url: "http://127.0.0.1:8010/api"
        enabled: true
      - server_id: 2
        name: "BBB服务器"
        api_url: "http://127.0.0.1:8011/api"
        enabled: true
    # 权限配置
    permissions:
      # 主人权限 - 拥有所有权限
      owners:
        - "123456789"  # QQ号示例
      # 超级管理员 - 拥有大部分管理权限
      super_admins:
        - "987654321"
        - "111222333"
      # 普通管理员 - 基础管理权限
      admins:
        - "444555666"
        - "777888999"
    # 允许使用的QQ群组
    allowed_groups:
      - "100000001"  # 管理群
      - "100000002"  # 玩家群
    # 功能权限配置
    features:
      # 是否允许踢人
      allow_kick: true
      # 是否允许封禁
      allow_ban: true
      # 是否允许换图
      allow_map_change: true
      # 是否允许查看玩家列表
      allow_player_list: true
      # 是否允许服务器管理
      allow_server_management: true

  # 服务器组B - 示例配置
  group_b:
    name: "服务器组B"
    description: "测试服务器组，用于新功能测试"
    game_servers:
      - server_id: 3
        name: "CCC测试服务器"
        api_url: "http://127.0.0.1:8012/api"
        enabled: true
      - server_id: 4
        name: "DDD开发服务器"
        api_url: "http://127.0.0.1:8013/api"
        enabled: false  # 暂时禁用
    permissions:
      owners:
        - "123456789"  # 可以跨组管理
      super_admins:
        - "555666777"
      admins:
        - "888999000"
    allowed_groups:
      - "200000001"  # 测试群
    features:
      allow_kick: true
      allow_ban: false  # 测试服务器不允许封禁
      allow_map_change: true
      allow_player_list: true
      allow_server_management: false

# 全局配置
global_settings:
  # 默认服务器组（当未指定组时使用）
  default_group: "group_a"
  # 是否启用跨组权限（主人可以管理所有组）
  enable_cross_group_permissions: true
  # 权限缓存时间（秒）
  permission_cache_time: 300
  # 是否记录权限操作日志
  log_permission_operations: true
  # 日志文件路径
  permission_log_file: "logs/permissions.log"

# 权限级别说明
# owner: 主人 - 拥有所有权限，可以管理其他管理员
# super_admin: 超级管理员 - 拥有大部分管理权限，不能管理主人和其他超级管理员
# admin: 普通管理员 - 基础管理权限，只能执行基本操作
# user: 普通用户 - 只能使用查询功能

# 功能权限说明
# allow_kick: 允许踢出玩家
# allow_ban: 允许封禁玩家
# allow_map_change: 允许更换地图
# allow_player_list: 允许查看玩家列表
# allow_server_management: 允许服务器管理操作（重启、配置等）